# Generated by Django 3.2.9 on 2021-12-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211217_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
